### ISSUE TITLE
'ann' Rust Crate

### ISSUE THREAD

**Issue by jesdazrez** [hilbert-space/ann#2]
Hi Ivan:

I'm developing an artificial neural network implementation in rust and I plan to publish it. I realized you are the owner of the 'ann' crate in crates.io and also noticed the repo has not seen activity in quite a long time.

I wonder if you would be willing to transfer ownership of such crate. You can find my code in https://gitlab.com/jesdazrez/ann

Regards, Jesús.

**Comment by IvanUkhov** [comment]
Hi Jesús! Yes, with pleasure. What is your username on crates.io?

**Comment by jesdazrez** [comment]
Hi. It's jesdazrez.

**Comment by IvanUkhov** [comment]
Done. Good luck!
